Yonderhon/config/routes.rb
Rails.application.routes.draw do
  root 'books#top'
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :index, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Yonderhon/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Yonderhon/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true, length: { maximum: 200 }
	validates :opinion, presence: true, length: { maximum: 200 }
end

Yonderhon/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :introduction, length: { maximum: 50 }
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }

 def email_required?
   false
 end
 def email_changed?
   false
 end

end

Yonderhon/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

    before_action :authenticate_user!, except: [:top]



	def after_sign_in_path_for(resource)
    	flash[:success] = 'Welcome! You have signed up successfully.'
  		user_path(current_user.id)
	end

	def after_sign_out_path_for(resource)
    	flash[:success] = 'Signed out successfully.'
  		root_path
	end

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   		devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
   		devise_parameter_sanitizer.permit(:account_update, keys: [:username])
	end



end

Yonderhon/app/controllers/books_controller.rb
class BooksController < ApplicationController


	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		@user = current_user
		@books = Book.all
		if @book.save
    	flash[:success] = 'Book was successfully created.'
		redirect_to book_path(@book.id)
		else
		render :index
		end
	end

	def show
		@user = current_user
		@user_book = Book.find(params[:id])
		@book = Book.new
	end

	def index
		@book = Book.new
		@books = Book.all

		@user = current_user
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user.id != current_user.id
			redirect_to books_path
		end
	end

	def update
		@book = Book.find(params[:id])
		@book.user_id = current_user.id
		if @book.update(book_params)
    	flash[:success] = 'Book was successfully updated.'
		redirect_to book_path(@book.id)
		else
			render :edit
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.user_id = current_user.id
		@book.destroy
    	flash[:success] = 'Book was successfully destroyed.'
		redirect_to books_path
	end

	private
	def book_params
		params.require(:book).permit(:title, :opinion)
	end

end

Yonderhon/app/controllers/users_controller.rb
class UsersController < ApplicationController


	def show
		@user = User.find(params[:id])
		@books = @user.books.page(params[:page]).reverse_order
		@book = Book.new
	end

	def index
		@users = User.all
		@book = Book.new

		@user = current_user
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
    		flash[:success] = 'profile was successfully updated.'
			redirect_to user_path(@user.id)
		else
			render :edit
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :profile_image ,:introduction)
	end

end

Yonderhon/app/helpers/application_helper.rb
module ApplicationHelper
end

Yonderhon/app/helpers/books_helper.rb
module BooksHelper
end

Yonderhon/app/helpers/users_helper.rb
module UsersHelper
end

Yonderhon/app/views/books/edit.html.erb

<div class="error_message">
<% if @book.errors.any? %>
  <p>errorです。</p>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
</div>





<h2>Editing book</h2>
<%= form_for(@book) do |f| %>
	<p>Title</p>
	<p><%= f.text_field :title, class: "book_title" %></p>
	<p>opinion</p>
	<p><%= f.text_area :opinion, class: "book_body" %></p>
	<p><%= f.submit 'Update Book' %></p>
<% end %>


<%= link_to "Show", book_path(@book.id), class: "book_#{@book.id}" %> |
<%= link_to "Back", books_path, class: "back" %>


Yonderhon/app/views/books/index.html.erb

<% if @book.errors.any? %>
  <p>errorです。</p>
  	<% @book.errors.full_messages.each do |message| %>
    <%= message %>
  	<% end %>
<% end %>


<p class="success_message"><%= flash[:success] %></p>


<div class="container">
	<div class="row">
		<div class="col-lg-4">


<h2>User info</h2>
<p><%= attachment_image_tag @user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %></p>
<table class="table">
	<tr>
		<td>name</td>
		<td><%= @user.name %></td>
	</tr>
	<tr>
		<td>introduction</td>
		<td><%= @user.introduction %></td>
	</tr>
</table>
<% if @user.id == current_user.id %>
	<p><%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %></p>
<% end %>





<h2>New book</h2>
<%= form_for(@book, url: books_path) do |f| %>
	<p>Title</p>
	<p><%= f.text_field :title, class: "book_title" %></p>
	<p>opinion</p>
	<p><%= f.text_area :opinion, class: "book_body" %></p>
	<p><%= f.submit 'Create Book' %></p>
<% end %>


		</div>
		<div class="col-lg-8">


<h2>Books</h2>
<table class="table table-hover table-inverse">
	<tr>
		<th></th>
		<th>Title</th>
		<th>Opinion</th>
	</tr>
	<% @books.each do |book| %>
	<tr>
		<td><%= link_to user_path(book.user), class: "user_#{book.user.id}" do %><%= attachment_image_tag book.user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %><% end %></td>
		<td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
		<td><%= book.opinion %></td>
	</tr>
	<% end %>
</table>


		</div>
	</div>
</div>

Yonderhon/app/views/books/show.html.erb

<p class="success_message"><%= flash[:success] %></p>


<div class="container">
	<div class="row">
		<div class="col-lg-4">


<h2>User info</h2>
<p><%= attachment_image_tag @user_book.user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %></p>
<table class="table">
	<tr>
		<td>name</td>
		<td><%= @user_book.user.name %></td>
	</tr>
	<tr>
		<td>introduction</td>
		<td><%= @user_book.user.introduction %></td>
	</tr>
</table>
<div class="row">
<% if @user_book.user.id == current_user.id %>
	<p><%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %></p>
<% else %>
	<p><%= link_to "", user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench user_#{current_user.id}" %></p>
<% end %>
</div>



<h2>New book</h2>
<%= form_for(@book, url: books_path, html: {method: "post"}) do |f| %>
	<p>Title</p>
	<p><%= f.text_field :title, class: "book_title" %></p>
	<p>opinion</p>
	<p><%= f.text_area :opinion, class: "book_body" %></p>
	<p><%= f.submit 'Create Book' %></p>
<% end %>


		</div>
		<div class="col-lg-8">



<h2>Book detail</h2>
<table class="table table-hover table-inverse">
	<tr>
		<td><%= link_to user_path(@user_book.user.id), class: "user_#{@user_book.user.id}" do %><%= attachment_image_tag @user_book.user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
			<% end %><br>
			<%= link_to @user_book.user.name, user_path(@user_book.user.id), class: "user_#{@user_book.user.id}" %>

		</td>
		<td><%= link_to @user_book.title, book_path(@user_book.id), class: "book_#{@user_book.id}" %></td>
		<td><%= @user_book.opinion %></td>

		<% if @user_book.user.id == current_user.id %>
			<td><%= link_to "Edit", edit_book_path(@user_book.id), class: "btn-sm btn-success edit_book_#{@user_book.id}" %></td>
			<td><%= link_to "Destroy", book_path(@user_book.id), method: :delete, "data-confirm" => "Are you sure?", class: "btn-sm btn-danger destroy_book_#{@user_book.id}" %></td>
		<% end %>
	</tr>
</table>



		</div>
	</div>
</div>

Yonderhon/app/views/books/top.html.erb

<p class="success_message"><%= flash[:success] %></p>


<h1>welcome to Bookers !!</h1>
<p>In Bookers,you can share and exchange your opinions , inpressions , and emotionsabout varioius books!</p>
<p><%= link_to "Log in", new_user_session_path, class: "sign_in" %></p>
<p><%= link_to "Sign Up", new_user_registration_path, class: "logout" %></p>

Yonderhon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yonderhon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="nav-content">
      <nav class="navbar-nav navbar-left">
        <p>Bookers</p>
      </nav>
      <nav class="navbar-nav navbar-right">

        <ul class="nav-list">
          <% if user_signed_in? %>
          <li class="nav-list-item"><%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home text-muted home" %></li>
          <li class="nav-list-item"><%= link_to " Users", users_path, class: "glyphicon glyphicon-user text-muted users" %></li>
          <li class="nav-list-item"><%= link_to " Books", books_path, class: "glyphicon glyphicon-book text-muted books" %></li>
          <li class="nav-list-item"><%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out text-muted logout"%></li>
          <% else %>
          <li class="nav-list-item"><%= link_to " Home", root_path, class: "glyphicon glyphicon-home text-muted home" %></li>
          <li class="nav-list-item"><%= link_to " About", root_path, class: "glyphicon glyphicon-link text-muted about" %></li>
          <li class="nav-list-item"><%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit text-muted sign_up" %></li>
          <li class="nav-list-item"><%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in text-muted sign_in" %></li>
          <% end %>
        </ul>
      </nav>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>

Yonderhon/app/views/users/edit.html.erb

<% if @user.errors.any? %>
  <p>errorです。</p>
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<h2>User info</h2>
<%= form_for(@user) do |f| %>
<%= f.text_field :name, autofocus: true, placeholder:"Name", class: "name" %>
<p>Image</p>
<p><%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user_image" %></p>
<p><%= f.text_area :introduction, autofocus: true, placeholder:"Introduction", class: "introduction" %></p>
<p><%= f.submit "Update User" %></p>
<% end %>

Yonderhon/app/views/users/index.html.erb

<div class="container">
	<div class="row">
		<div class="col-lg-4">


<h2>User info</h2>
<p><%= attachment_image_tag @user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %></p>
<table class="table">
	<tr>
		<td>name</td>
		<td><%= @user.name %></td>
	</tr>
	<tr>
		<td>introduction</td>
		<td><%= @user.introduction %></td>
	</tr>
</table>
<% if @user.id == current_user.id %>
	<p><%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %></p>
<% end %>




<h2>New book</h2>
<%= form_for(@book, url: books_path) do |f| %>
	<p>Title</p>
	<p><%= f.text_field :title, class: "book_title" %></p>
	<p>opinion</p>
	<p><%= f.text_area :opinion, class: "book_body" %></p>
	<p><%= f.submit 'Create Book' %></p>
<% end %>


		</div>
		<div class="col-lg-8">


<h2>Users</h2>
<table class="table table-hover table-inverse">
	<tr>
		<th>image</th>
		<th>name</th>
		<th></th>
	</tr>
<% @users.each do |user| %>
	<tr>
		<td><%= attachment_image_tag user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></td>
		<td><%= user.name %></td>
		<td><%= link_to "Show", user_path(user.id), class: "user_#{user.id}" %></td>
	</tr>
<% end %>
</table>



		</div>
	</div>
</div>

Yonderhon/app/views/users/show.html.erb
<p class="success_message"><%= flash[:success] %></p>


<div class="container">
	<div class="row">
		<div class="col-lg-4">


<h2>User info</h2>
<p><%= attachment_image_tag @user, :profile_image,　format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %></p>
<table class="table">
	<tr>
		<td>name</td>
		<td><%= @user.name %></td>
	</tr>
	<tr>
		<td>introduction</td>
		<td><%= @user.introduction %></td>
	</tr>
</table>
<% if @user.id == current_user.id %>
	<p><%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %></p>
<% else %>
	<p><%= link_to "", user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench user_#{current_user.id}" %></p>
<% end %>


<h2>New book</h2>
<%= form_for(@book, url: books_path) do |f| %>
	<p>Title</p>
	<p><%= f.text_field :title, class: "book_title" %></p>
	<p>opinion</p>
	<p><%= f.text_area :opinion, class: "book_body" %></p>
	<p><%= f.submit 'Create Book' %></p>
<% end %>


		</div>
		<div class="col-lg-8">


<h2>Books</h2>
<table class="table table-hover table-inverse">
	<tr>
		<th></th>
		<th>Title</th>
		<th>Opinion</th>
	</tr>
<% @books.each do |book| %>
	<tr>
		<td><%= link_to user_path(book.user), class: "user_#{book.user.id}" do %><%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %><% end %></td>
		<td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
		<td><%= book.opinion %></td>
	</tr>
<%= paginate @books, class: "pagenate" %>
<% end %>
</table>


		</div>
	</div>
</div>